echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Git"
echo "I am learning GitHub with batch-32"
echo "I have started my career in DevOps"
echo "I am learning GitHub with batch-33"
echo "I am learning GitHub with batch-32 and I am loving it"
echo "I am learning GitHub with batch-33 and I am loving it"
echo "I am learning DevOps with batch-32 and I am loving it"